@startuml usecases

actor Manager
actor Passenger
actor Person
actor Employee

usecase "Buy a ticket" as buyTicket
usecase "Take a bus" as takeBus
usecase "Work in a ticket window" as ticketWindow
usecase "Send a bus to garage" as sendBusToGarage
usecase "Edit a route" as editRoute
usecase "Change route number" as changeRouteNumber
usecase "Change route stations" as changeRouteStations
usecase "Change route arrival timestamps" as changeRouteArrivalTimestamps


Passenger --|> Person
Employee --|> Person
Manager --|> Employee

changeRouteArrivalTimestamps --|> editRoute
changeRouteNumber --|> editRoute
changeRouteStations --|> editRoute

Manager -- editRoute
Manager -- sendBusToGarage

Employee -- ticketWindow

Passenger -- buyTicket
Passenger -- takeBus

@enduml